### ISSUE TITLE
Feat: mock readWorkbookById API

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote_client#11]
### 🤔 Description

* `readWorkbookById` API mock과 관련된 UI를 구현한다.

### 📌 ToDo

> **UI**
>
> - [X] 문제집 정보에 대한 간단한 UI 구현
> - [X] 외의 문제집 상세 페이지의 간단한 UI 구현
> - [x] 돌아가기 라우팅 구현
> - [X] 문제집 상세 페이지에 대한 라우팅 구현

> **Mocking**
>
> - [X] API 성공 상태 mocking
> - [X] API 실패 상태 mocking

### 💬 Others

* 와이어프레임 만들기 너무 싫네요..😭

**Comment by RinRinPARK** [comment]
화이팅~~~
